spring:
  datasource:
    url: jdbc:h2:file:~/deploy-manager/h2db/h2_database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

pagination:
  limit:
    default: 6