spring:
  datasource:
    url: jdbc:h2:file:~/deploy-manager/h2db/h2_database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#
hidden:
  file:
<<<<<<< HEAD
    path: "project/src/main/resources/hidden/hidden.json"
=======
    path: "/home/daniel/Programs/java/IfLostFind/project/src/main/resources/hidden/hidden.json"
>>>>>>> c325aac74ca57a86bd5290f2b7df889c3996dd1e
